# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '0926.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(411, 610)
        font = QFont()
        font.setFamilies([u"KOTRA_BOLD"])
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color :rgb(255, 255, 255)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.xmlPath = QLineEdit(self.centralwidget)
        self.xmlPath.setObjectName(u"xmlPath")
        self.xmlPath.setGeometry(QRect(50, 181, 231, 41))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 216))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(249, 249, 249, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(1, 1, 1, 216))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush3 = QBrush(QColor(65, 65, 65, 63))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush5 = QBrush(QColor(255, 255, 255, 63))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.xmlPath.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Roboto Flex"])
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.xmlPath.setFont(font1)
        self.xmlPath.setMouseTracking(True)
        self.xmlPath.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.xmlPath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.xmlPath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.xmlPath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.xmlPath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.xmlPath.setAutoFillBackground(False)
        self.xmlPath.setStyleSheet(u"border-radius : 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px; ")
        self.xmlPath.setInputMask(u"")
        self.xmlPath.setText(u"")
        self.xmlPath.setFrame(True)
        self.xmlPath.setReadOnly(True)
        self.xmlPath.setPlaceholderText(u".fcpxml file ONLY")
        self.xmlPath.setClearButtonEnabled(False)
        self.xml_upload = QPushButton(self.centralwidget)
        self.xml_upload.setObjectName(u"xml_upload")
        self.xml_upload.setGeometry(QRect(270, 181, 91, 41))
        font2 = QFont()
        font2.setFamilies([u"SUIT"])
        font2.setBold(True)
        self.xml_upload.setFont(font2)
        self.xml_upload.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.xml_upload.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.xml_upload.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.xml_upload.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.xml_upload.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.xml_upload.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : white;\n"
"border : 1.3px solid rgb(213, 213, 213);\n"
"color : rgb(147, 147, 147); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(91, 134, 255);\n"
"	border :1.3px solid rgb(91, 134, 255);\n"
"}")
        self.li_upload = QPushButton(self.centralwidget)
        self.li_upload.setObjectName(u"li_upload")
        self.li_upload.setGeometry(QRect(270, 290, 91, 41))
        self.li_upload.setFont(font2)
        self.li_upload.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.li_upload.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.li_upload.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.li_upload.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.li_upload.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.li_upload.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : white;\n"
"border : 1.3px solid rgb(213, 213, 213);\n"
"color : rgb(147, 147, 147); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(91, 134, 255);\n"
"	border :1.3px solid rgb(91, 134, 255);\n"
"}")
        self.linePath = QLineEdit(self.centralwidget)
        self.linePath.setObjectName(u"linePath")
        self.linePath.setGeometry(QRect(50, 290, 231, 41))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.linePath.setPalette(palette1)
        font3 = QFont()
        font3.setFamilies([u"Roboto Flex"])
        self.linePath.setFont(font3)
#if QT_CONFIG(tooltip)
        self.linePath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.linePath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.linePath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.linePath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.linePath.setStyleSheet(u"border-radius : 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px;")
        self.linePath.setInputMask(u"")
        self.linePath.setText(u"")
        self.linePath.setReadOnly(True)
        self.linePath.setPlaceholderText(u".xlsx file ONLY")
        self.shot_name = QLineEdit(self.centralwidget)
        self.shot_name.setObjectName(u"shot_name")
        self.shot_name.setGeometry(QRect(50, 400, 311, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.shot_name.setPalette(palette2)
        self.shot_name.setFont(font3)
#if QT_CONFIG(tooltip)
        self.shot_name.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.shot_name.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.shot_name.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.shot_name.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.shot_name.setStyleSheet(u" border-radius : 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px; ")
        self.shot_name.setInputMask(u"")
        self.shot_name.setText(u"")
        self.shot_name.setPlaceholderText(u"XXX for XXX_1234")
        self.shot_name.setClearButtonEnabled(True)
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(160, 510, 101, 41))
        self.start.setFont(font2)
        self.start.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : rgb(91, 134, 255);\n"
"color : white; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(71, 104, 200);\n"
"}")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 141, 61, 41))
        font4 = QFont()
        font4.setFamilies([u"Roboto Flex"])
        font4.setPointSize(16)
        font4.setBold(True)
        self.label.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label.setStyleSheet(u"font-weight : 600;\n"
"color : black")
        self.label.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 41, 411, 51))
        font5 = QFont()
        font5.setFamilies([u"Roboto Flex"])
        font5.setPointSize(32)
        font5.setBold(True)
        font5.setItalic(False)
        self.label_6.setFont(font5)
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_6.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_6.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_6.setStyleSheet(u"font-weight : 900;\n"
"color : black;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 250, 91, 41))
        self.label_2.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_2.setStyleSheet(u"font-weight : 600;\n"
"color : black;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 360, 81, 41))
        self.label_3.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_3.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_3.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_3.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_3.setStyleSheet(u"font-weight : 600;\n"
"color : black;")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 80, 411, 31))
        font6 = QFont()
        font6.setFamilies([u"Roboto Flex"])
        font6.setPointSize(14)
        font6.setBold(False)
        self.label_8.setFont(font6)
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_8.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_8.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_8.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_8.setStyleSheet(u"color : gray;\n"
"font-weight : 300;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.Done = QLabel(self.centralwidget)
        self.Done.setObjectName(u"Done")
        self.Done.setGeometry(QRect(160, 550, 101, 31))
        self.Done.setFont(font3)
#if QT_CONFIG(tooltip)
        self.Done.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done.setStyleSheet(u"color : green")
        self.Done.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Done.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.linePath.raise_()
        self.xmlPath.raise_()
        self.xml_upload.raise_()
        self.li_upload.raise_()
        self.shot_name.raise_()
        self.start.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Burn In Tool", None))
        self.xml_upload.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.li_upload.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"XML file", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"SHOT BURN-IN", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Rename list", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"SEQ name", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Davinci Resolve shot name burn-in tool", None))
        self.Done.setText(QCoreApplication.translate("MainWindow", u"Done !", None))
    # retranslateUi

