# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '1014.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(422, 466)
        font = QFont()
        font.setFamilies([u"KOTRA_BOLD"])
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color :rgb(255, 255, 255)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.edlpath = QLineEdit(self.centralwidget)
        self.edlpath.setObjectName(u"edlpath")
        self.edlpath.setGeometry(QRect(50, 181, 241, 41))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 216))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(249, 249, 249, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(1, 1, 1, 216))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush3 = QBrush(QColor(65, 65, 65, 63))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush5 = QBrush(QColor(255, 255, 255, 63))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.edlpath.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Roboto Flex"])
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.edlpath.setFont(font1)
        self.edlpath.setMouseTracking(True)
        self.edlpath.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.edlpath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.edlpath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.edlpath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.edlpath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.edlpath.setAutoFillBackground(False)
        self.edlpath.setStyleSheet(u"border-radius : 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px; ")
        self.edlpath.setInputMask(u"")
        self.edlpath.setText(u"")
        self.edlpath.setFrame(True)
        self.edlpath.setReadOnly(True)
        self.edlpath.setPlaceholderText(u"*.edl")
        self.edlpath.setClearButtonEnabled(False)
        self.upload = QPushButton(self.centralwidget)
        self.upload.setObjectName(u"upload")
        self.upload.setGeometry(QRect(280, 181, 91, 41))
        font2 = QFont()
        font2.setFamilies([u"SUIT"])
        font2.setBold(True)
        self.upload.setFont(font2)
        self.upload.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.upload.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.upload.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.upload.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.upload.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.upload.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : white;\n"
"border : 1.3px solid rgb(213, 213, 213);\n"
"color : rgb(147, 147, 147); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(91, 134, 255);\n"
"	border :1.3px solid rgb(91, 134, 255);\n"
"}")
        self.linePath = QLineEdit(self.centralwidget)
        self.linePath.setObjectName(u"linePath")
        self.linePath.setGeometry(QRect(50, 280, 321, 41))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.linePath.setPalette(palette1)
        font3 = QFont()
        font3.setFamilies([u"Roboto Flex"])
        self.linePath.setFont(font3)
#if QT_CONFIG(tooltip)
        self.linePath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.linePath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.linePath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.linePath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.linePath.setStyleSheet(u"border-radius : 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px;")
        self.linePath.setInputMask(u"")
        self.linePath.setText(u"")
        self.linePath.setReadOnly(False)
        self.linePath.setPlaceholderText(u"00:00:00:00")
        self.linePath.setClearButtonEnabled(True)
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(160, 370, 101, 41))
        self.start.setFont(font2)
        self.start.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : rgb(91, 134, 255);\n"
"color : white; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(71, 104, 200);\n"
"}")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 141, 61, 41))
        font4 = QFont()
        font4.setFamilies([u"Roboto Flex"])
        font4.setPointSize(16)
        font4.setBold(True)
        self.label.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label.setStyleSheet(u"font-weight : 600;\n"
"color : black")
        self.label.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 41, 411, 51))
        font5 = QFont()
        font5.setFamilies([u"Roboto Flex"])
        font5.setPointSize(32)
        font5.setBold(True)
        font5.setItalic(False)
        self.label_6.setFont(font5)
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_6.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_6.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_6.setStyleSheet(u"font-weight : 900;\n"
"color : black;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 240, 71, 41))
        self.label_2.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_2.setStyleSheet(u"font-weight : 600;\n"
"color : black;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 80, 411, 31))
        font6 = QFont()
        font6.setFamilies([u"Roboto Flex"])
        font6.setPointSize(14)
        font6.setBold(False)
        self.label_8.setFont(font6)
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_8.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_8.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_8.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_8.setStyleSheet(u"color : gray;\n"
"font-weight : 300;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.Done = QLabel(self.centralwidget)
        self.Done.setObjectName(u"Done")
        self.Done.setGeometry(QRect(0, 410, 421, 31))
        self.Done.setFont(font3)
#if QT_CONFIG(tooltip)
        self.Done.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done.setStyleSheet(u"color : green")
        self.Done.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Done.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.linePath.raise_()
        self.edlpath.raise_()
        self.upload.raise_()
        self.start.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"1C-Razor", None))
        self.upload.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"EDL file", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"1C RAZOR", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Start TC", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Cut clips in Davinci Resolve using EDL", None))
        self.Done.setText(QCoreApplication.translate("MainWindow", u"[ razor_output.edl ] has been created.", None))
    # retranslateUi

