# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ToolArchivesAxAyiI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(563, 514)
        font = QFont()
        font.setFamilies([u"KOTRA_BOLD"])
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setCursor(QCursor(Qt.ArrowCursor))
        MainWindow.setStyleSheet(u"background-color : rgb(169, 181, 189)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Tab = QTabWidget(self.centralwidget)
        self.Tab.setObjectName(u"Tab")
        self.Tab.setGeometry(QRect(30, 120, 501, 341))
        font1 = QFont()
        font1.setFamilies([u"SUIT"])
        font1.setBold(True)
        tab_bar = self.Tab.tabBar()
        tab_bar.setCursor(QCursor(Qt.PointingHandCursor))
        self.Tab.setFont(font1)
        self.Tab.setCursor(QCursor(Qt.ArrowCursor))
        self.Tab.setMouseTracking(False)
        self.Tab.setFocusPolicy(Qt.TabFocus)
        self.Tab.setStyleSheet(u"		QTabWidget::pane {\n"
"border: 3px solid rgb(58, 64, 68);\n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"border-top-left-radius : 5px;\n"
"border-top-right-radius : 5px;\n"
"         }\n"
"\n"
"         QTabWidget::tab-bar {\n"
"             left: 0px;\n"
"         }\n"
"\n"
"         QTabBar::tab {\n"
"             background: rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68);\n"
"border: 1px solid rgb(58, 64, 68);\n"
"             border-top-left-radius: 5px;\n"
"             border-top-right-radius: 5px;\n"
"             min-width: 8.5ex;\n"
"             padding: 7px;\n"
"margin-left : 4px;\n"
"\n"
"         }\n"
"\n"
"         QTabBar::tab:selected, QTabBar::tab:hover {\n"
"             background: rgb(58, 64, 68);\n"
"			color : rgb(169, 181, 189);\n"
"             border-top-left-radius: 5px;\n"
"             border-top-right-radius: 5px;\n"
"         }\n"
"\n"
"         QTabBar::tab:selected {\n"
"             border-bottom-color: rgb(58, 64, 68);\n"
"         }\n"
"\n"
""
                        "         QTabBar::tab:!selected {\n"
"             margin-top: 4px; \n"
"         }\n"
"\n"
"\n"
"#HI {\n"
"background : rgb(58, 64, 68); }\n"
"#edl2xlsx {\n"
"background : rgb(58, 64, 68); }\n"
"#xml2xlsx {\n"
"background : rgb(58, 64, 68); }\n"
"#rename {\n"
"background : rgb(58, 64, 68); }\n"
"#burnIn {\n"
"background : rgb(58, 64, 68); }\n"
"#exrSize {\n"
"background : rgb(58, 64, 68); }")
        self.Tab.setUsesScrollButtons(False)
        self.Tab.setDocumentMode(False)
        self.Tab.setTabsClosable(False)
        self.Tab.setMovable(True)
        self.edl2xlsx = QWidget()
        self.edl2xlsx.setObjectName(u"edl2xlsx")
        self.label_16 = QLabel(self.edl2xlsx)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(-10, 60, 511, 31))
        font2 = QFont()
        font2.setFamilies([u"Roboto Flex"])
        font2.setPointSize(14)
        font2.setBold(False)
        self.label_16.setFont(font2)
#if QT_CONFIG(tooltip)
        self.label_16.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_16.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_16.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_16.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_16.setStyleSheet(u"color : #A9B5BD;\n"
"font-weight : 300;\n"
"background : transparent;")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.edl2xlsx)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 20, 491, 51))
        font3 = QFont()
        font3.setFamilies([u"Roboto Flex"])
        font3.setPointSize(32)
        font3.setBold(True)
        font3.setItalic(False)
        self.label_17.setFont(font3)
#if QT_CONFIG(tooltip)
        self.label_17.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_17.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_17.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_17.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_17.setStyleSheet(u"font-weight : 900;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_17.setAlignment(Qt.AlignCenter)
        self.start_e2x = QPushButton(self.edl2xlsx)
        self.start_e2x.setObjectName(u"start_e2x")
        self.start_e2x.setGeometry(QRect(200, 240, 101, 41))
        self.start_e2x.setFont(font1)
        self.start_e2x.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start_e2x.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start_e2x.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start_e2x.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start_e2x.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start_e2x.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : #3A4044;\n"
"color : #A9B5BD;\n"
"border: 1px solid #A9B5BD; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68)\n"
"}")
        self.Done_e2x = QLabel(self.edl2xlsx)
        self.Done_e2x.setObjectName(u"Done_e2x")
        self.Done_e2x.setGeometry(QRect(40, 210, 421, 31))
        font4 = QFont()
        font4.setFamilies([u"Roboto Flex"])
        self.Done_e2x.setFont(font4)
#if QT_CONFIG(tooltip)
        self.Done_e2x.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done_e2x.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done_e2x.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done_e2x.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done_e2x.setStyleSheet(u"color : rgb(140, 189, 154);\n"
"background : transparent;")
        self.Done_e2x.setAlignment(Qt.AlignCenter)
        self.upload_e2x = QPushButton(self.edl2xlsx)
        self.upload_e2x.setObjectName(u"upload_e2x")
        self.upload_e2x.setGeometry(QRect(360, 140, 91, 41))
        self.upload_e2x.setFont(font1)
        self.upload_e2x.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.upload_e2x.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.upload_e2x.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.upload_e2x.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.upload_e2x.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.upload_e2x.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.label_2 = QLabel(self.edl2xlsx)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 100, 91, 41))
        font5 = QFont()
        font5.setFamilies([u"Roboto Flex"])
        font5.setPointSize(16)
        font5.setBold(True)
        self.label_2.setFont(font5)
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_2.setStyleSheet(u"font-weight : 600;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.edlpath = QLineEdit(self.edl2xlsx)
        self.edlpath.setObjectName(u"edlpath")
        self.edlpath.setGeometry(QRect(50, 140, 321, 41))
        palette = QPalette()
        brush = QBrush(QColor(169, 181, 189, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(58, 64, 68, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush2 = QBrush(QColor(169, 181, 189, 128))
        brush2.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.edlpath.setPalette(palette)
        font6 = QFont()
        font6.setFamilies([u"Roboto Flex"])
        font6.setKerning(True)
        font6.setStyleStrategy(QFont.PreferDefault)
        self.edlpath.setFont(font6)
        self.edlpath.setMouseTracking(True)
        self.edlpath.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.edlpath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.edlpath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.edlpath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.edlpath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.edlpath.setAutoFillBackground(False)
        self.edlpath.setStyleSheet(u"border-radius : 7px;\n"
"background : #3A4044;\n"
"border : 1px solid #A9B5BD;\n"
"padding-left : 10px; \n"
"color : rgb(169, 181, 189)")
        self.edlpath.setInputMask(u"")
        self.edlpath.setText(u"")
        self.edlpath.setFrame(True)
        self.edlpath.setReadOnly(True)
        self.edlpath.setPlaceholderText(u"EDL only")
        self.edlpath.setClearButtonEnabled(False)
        self.Tab.addTab(self.edl2xlsx, "")
        self.label_16.raise_()
        self.label_17.raise_()
        self.start_e2x.raise_()
        self.Done_e2x.raise_()
        self.label_2.raise_()
        self.edlpath.raise_()
        self.upload_e2x.raise_()
        self.xml2xlsx = QWidget()
        self.xml2xlsx.setObjectName(u"xml2xlsx")
        self.label_14 = QLabel(self.xml2xlsx)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 20, 491, 51))
        self.label_14.setFont(font3)
#if QT_CONFIG(tooltip)
        self.label_14.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_14.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_14.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_14.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_14.setStyleSheet(u"font-weight : 900;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.xml2xlsx)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(-10, 60, 511, 31))
        self.label_15.setFont(font2)
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_15.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_15.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_15.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_15.setStyleSheet(u"color : #A9B5BD;\n"
"font-weight : 300;\n"
"background : transparent;")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.start_x2x = QPushButton(self.xml2xlsx)
        self.start_x2x.setObjectName(u"start_x2x")
        self.start_x2x.setGeometry(QRect(200, 240, 101, 41))
        self.start_x2x.setFont(font1)
        self.start_x2x.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start_x2x.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start_x2x.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start_x2x.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start_x2x.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start_x2x.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : #3A4044;\n"
"color : #A9B5BD;\n"
"border: 1px solid #A9B5BD; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68)\n"
"}")
        self.Done_x2x = QLabel(self.xml2xlsx)
        self.Done_x2x.setObjectName(u"Done_x2x")
        self.Done_x2x.setGeometry(QRect(40, 210, 421, 31))
        self.Done_x2x.setFont(font4)
#if QT_CONFIG(tooltip)
        self.Done_x2x.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done_x2x.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done_x2x.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done_x2x.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done_x2x.setStyleSheet(u"color : rgb(140, 189, 154);\n"
"background : transparent;")
        self.Done_x2x.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.xml2xlsx)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 100, 91, 41))
        self.label_3.setFont(font5)
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_3.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_3.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_3.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_3.setStyleSheet(u"font-weight : 600;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.xmlpath = QLineEdit(self.xml2xlsx)
        self.xmlpath.setObjectName(u"xmlpath")
        self.xmlpath.setGeometry(QRect(50, 140, 321, 41))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.xmlpath.setPalette(palette1)
        self.xmlpath.setFont(font6)
        self.xmlpath.setMouseTracking(True)
        self.xmlpath.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.xmlpath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.xmlpath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.xmlpath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.xmlpath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.xmlpath.setAutoFillBackground(False)
        self.xmlpath.setStyleSheet(u"border-radius : 7px;\n"
"background : #3A4044;\n"
"border : 1px solid #A9B5BD;\n"
"padding-left : 10px; \n"
"color : rgb(169, 181, 189)")
        self.xmlpath.setInputMask(u"")
        self.xmlpath.setText(u"")
        self.xmlpath.setFrame(True)
        self.xmlpath.setReadOnly(True)
        self.xmlpath.setPlaceholderText(u"XML only")
        self.xmlpath.setClearButtonEnabled(False)
        self.upload_x2x = QPushButton(self.xml2xlsx)
        self.upload_x2x.setObjectName(u"upload_x2x")
        self.upload_x2x.setGeometry(QRect(360, 140, 91, 41))
        self.upload_x2x.setFont(font1)
        self.upload_x2x.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.upload_x2x.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.upload_x2x.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.upload_x2x.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.upload_x2x.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.upload_x2x.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.Tab.addTab(self.xml2xlsx, "")
        self.rename = QWidget()
        self.rename.setObjectName(u"rename")
        self.label_12 = QLabel(self.rename)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 20, 461, 51))
        self.label_12.setFont(font3)
#if QT_CONFIG(tooltip)
        self.label_12.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_12.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_12.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_12.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_12.setStyleSheet(u"font-weight : 900;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.rename)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(-10, 60, 521, 31))
        font7 = QFont()
        font7.setFamilies([u"Roboto Flex"])
        font7.setPointSize(14)
        font7.setBold(True)
        self.label_13.setFont(font7)
#if QT_CONFIG(tooltip)
        self.label_13.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_13.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_13.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_13.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_13.setStyleSheet(u"color : rgb(255, 132, 116);\n"
"font-weight : 800;\n"
"background : transparent;")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.start_RN = QPushButton(self.rename)
        self.start_RN.setObjectName(u"start_RN")
        self.start_RN.setGeometry(QRect(200, 240, 101, 41))
        self.start_RN.setFont(font1)
        self.start_RN.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start_RN.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start_RN.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start_RN.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start_RN.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start_RN.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : #3A4044;\n"
"color : #A9B5BD;\n"
"border: 1px solid #A9B5BD; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68)\n"
"}")
        self.Done_RN = QLabel(self.rename)
        self.Done_RN.setObjectName(u"Done_RN")
        self.Done_RN.setGeometry(QRect(40, 210, 421, 31))
        self.Done_RN.setFont(font4)
#if QT_CONFIG(tooltip)
        self.Done_RN.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done_RN.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done_RN.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done_RN.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done_RN.setStyleSheet(u"color : rgb(140, 189, 154);\n"
"background : transparent;")
        self.Done_RN.setAlignment(Qt.AlignCenter)
        self.list_RN = QPushButton(self.rename)
        self.list_RN.setObjectName(u"list_RN")
        self.list_RN.setGeometry(QRect(29, 130, 91, 41))
        self.list_RN.setFont(font1)
        self.list_RN.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.list_RN.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.list_RN.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.list_RN.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.list_RN.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.list_RN.setStyleSheet(u"QPushButton {\n"
"border-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.list_label_RN = QLabel(self.rename)
        self.list_label_RN.setObjectName(u"list_label_RN")
        self.list_label_RN.setGeometry(QRect(19, 170, 111, 21))
        font8 = QFont()
        font8.setFamilies([u"Roboto Flex"])
        font8.setPointSize(10)
        self.list_label_RN.setFont(font8)
#if QT_CONFIG(tooltip)
        self.list_label_RN.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.list_label_RN.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.list_label_RN.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.list_label_RN.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.list_label_RN.setStyleSheet(u"color : rgb(169, 181, 189);\n"
"background : transparent;")
        self.list_label_RN.setAlignment(Qt.AlignCenter)
        self.ext_path = QLineEdit(self.rename)
        self.ext_path.setObjectName(u"ext_path")
        self.ext_path.setGeometry(QRect(150, 129, 194, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.ext_path.setPalette(palette2)
        self.ext_path.setFont(font6)
        self.ext_path.setMouseTracking(True)
        self.ext_path.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.ext_path.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.ext_path.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.ext_path.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ext_path.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.ext_path.setAutoFillBackground(False)
        self.ext_path.setStyleSheet(u"border-radius : 7px;\n"
"background : #3A4044;\n"
"border : 1px solid #A9B5BD;\n"
"padding-left : 10px; \n"
"color : rgb(169, 181, 189)")
        self.ext_path.setInputMask(u"")
        self.ext_path.setText(u"")
        self.ext_path.setFrame(True)
        self.ext_path.setReadOnly(False)
        self.ext_path.setClearButtonEnabled(True)
        self.folder_label_RN = QLabel(self.rename)
        self.folder_label_RN.setObjectName(u"folder_label_RN")
        self.folder_label_RN.setGeometry(QRect(364, 170, 111, 21))
        self.folder_label_RN.setFont(font8)
#if QT_CONFIG(tooltip)
        self.folder_label_RN.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.folder_label_RN.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.folder_label_RN.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.folder_label_RN.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.folder_label_RN.setStyleSheet(u"color : rgb(169, 181, 189);\n"
"background : transparent;")
        self.folder_label_RN.setAlignment(Qt.AlignCenter)
        self.folder_RN_2 = QPushButton(self.rename)
        self.folder_RN_2.setObjectName(u"folder_RN_2")
        self.folder_RN_2.setGeometry(QRect(374, 130, 91, 41))
        self.folder_RN_2.setFont(font1)
        self.folder_RN_2.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.folder_RN_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.folder_RN_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.folder_RN_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.folder_RN_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.folder_RN_2.setStyleSheet(u"QPushButton {\n"
"border-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.Tab.addTab(self.rename, "")
        self.burnIn = QWidget()
        self.burnIn.setObjectName(u"burnIn")
        self.label_10 = QLabel(self.burnIn)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 20, 421, 51))
        self.label_10.setFont(font3)
#if QT_CONFIG(tooltip)
        self.label_10.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_10.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_10.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_10.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_10.setStyleSheet(u"font-weight : 900;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.burnIn)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 60, 481, 31))
        self.label_11.setFont(font2)
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_11.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_11.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_11.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_11.setStyleSheet(u"color : #A9B5BD;\n"
"font-weight : 300;\n"
"background : transparent;")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.start_BI = QPushButton(self.burnIn)
        self.start_BI.setObjectName(u"start_BI")
        self.start_BI.setGeometry(QRect(200, 240, 101, 41))
        self.start_BI.setFont(font1)
        self.start_BI.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start_BI.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start_BI.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start_BI.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start_BI.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start_BI.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : #3A4044;\n"
"color : #A9B5BD;\n"
"border: 1px solid #A9B5BD; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68)\n"
"}")
        self.Done_BI = QLabel(self.burnIn)
        self.Done_BI.setObjectName(u"Done_BI")
        self.Done_BI.setGeometry(QRect(40, 210, 421, 31))
        self.Done_BI.setFont(font4)
#if QT_CONFIG(tooltip)
        self.Done_BI.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done_BI.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done_BI.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done_BI.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done_BI.setStyleSheet(u"color : rgb(140, 189, 154);\n"
"background : transparent;")
        self.Done_BI.setAlignment(Qt.AlignCenter)
        self.list_BI = QPushButton(self.burnIn)
        self.list_BI.setObjectName(u"list_BI")
        self.list_BI.setGeometry(QRect(29, 130, 91, 41))
        self.list_BI.setFont(font1)
        self.list_BI.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.list_BI.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.list_BI.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.list_BI.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.list_BI.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.list_BI.setStyleSheet(u"QPushButton {\n"
"border-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.xml_BI = QPushButton(self.burnIn)
        self.xml_BI.setObjectName(u"xml_BI")
        self.xml_BI.setGeometry(QRect(374, 130, 91, 41))
        self.xml_BI.setFont(font1)
        self.xml_BI.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.xml_BI.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.xml_BI.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.xml_BI.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.xml_BI.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.xml_BI.setStyleSheet(u"QPushButton {\n"
"border-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.list_label_BI = QLabel(self.burnIn)
        self.list_label_BI.setObjectName(u"list_label_BI")
        self.list_label_BI.setGeometry(QRect(19, 170, 111, 21))
        self.list_label_BI.setFont(font8)
#if QT_CONFIG(tooltip)
        self.list_label_BI.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.list_label_BI.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.list_label_BI.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.list_label_BI.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.list_label_BI.setStyleSheet(u"color : rgb(169, 181, 189);\n"
"background : transparent;")
        self.list_label_BI.setAlignment(Qt.AlignCenter)
        self.xml_label_BI = QLabel(self.burnIn)
        self.xml_label_BI.setObjectName(u"xml_label_BI")
        self.xml_label_BI.setGeometry(QRect(364, 170, 111, 21))
        self.xml_label_BI.setFont(font8)
#if QT_CONFIG(tooltip)
        self.xml_label_BI.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.xml_label_BI.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.xml_label_BI.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.xml_label_BI.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.xml_label_BI.setStyleSheet(u"color : rgb(169, 181, 189);\n"
"background : transparent;")
        self.xml_label_BI.setAlignment(Qt.AlignCenter)
        self.shot_name = QLineEdit(self.burnIn)
        self.shot_name.setObjectName(u"shot_name")
        self.shot_name.setGeometry(QRect(154, 129, 187, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.shot_name.setPalette(palette3)
        self.shot_name.setFont(font6)
        self.shot_name.setMouseTracking(True)
        self.shot_name.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.shot_name.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.shot_name.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.shot_name.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.shot_name.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.shot_name.setAutoFillBackground(False)
        self.shot_name.setStyleSheet(u"border-radius : 7px;\n"
"background : #3A4044;\n"
"border : 1px solid #A9B5BD;\n"
"padding-left : 10px; \n"
"color : rgb(169, 181, 189)")
        self.shot_name.setInputMask(u"")
        self.shot_name.setText(u"")
        self.shot_name.setFrame(True)
        self.shot_name.setReadOnly(False)
        self.shot_name.setClearButtonEnabled(True)
        self.Tab.addTab(self.burnIn, "")
        self.exrSize = QWidget()
        self.exrSize.setObjectName(u"exrSize")
        self.exrpath = QLineEdit(self.exrSize)
        self.exrpath.setObjectName(u"exrpath")
        self.exrpath.setGeometry(QRect(50, 140, 321, 41))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.exrpath.setPalette(palette4)
        self.exrpath.setFont(font6)
        self.exrpath.setMouseTracking(True)
        self.exrpath.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.exrpath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.exrpath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.exrpath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.exrpath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.exrpath.setAutoFillBackground(False)
        self.exrpath.setStyleSheet(u"border-radius : 7px;\n"
"background : #3A4044;\n"
"border : 1px solid #A9B5BD;\n"
"padding-left : 10px; \n"
"color : rgb(169, 181, 189)")
        self.exrpath.setInputMask(u"")
        self.exrpath.setText(u"")
        self.exrpath.setFrame(True)
        self.exrpath.setReadOnly(True)
        self.exrpath.setClearButtonEnabled(False)
        self.Done_size = QLabel(self.exrSize)
        self.Done_size.setObjectName(u"Done_size")
        self.Done_size.setGeometry(QRect(40, 210, 421, 31))
        self.Done_size.setFont(font4)
#if QT_CONFIG(tooltip)
        self.Done_size.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done_size.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done_size.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done_size.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done_size.setStyleSheet(u"color : rgb(140, 189, 154);\n"
"background : transparent;")
        self.Done_size.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.exrSize)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 100, 91, 41))
        self.label_4.setFont(font5)
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_4.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_4.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_4.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_4.setStyleSheet(u"font-weight : 600;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.upload_pc_2 = QPushButton(self.exrSize)
        self.upload_pc_2.setObjectName(u"upload_pc_2")
        self.upload_pc_2.setGeometry(QRect(360, 140, 91, 41))
        self.upload_pc_2.setFont(font1)
        self.upload_pc_2.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.upload_pc_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.upload_pc_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.upload_pc_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.upload_pc_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.upload_pc_2.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.start_size = QPushButton(self.exrSize)
        self.start_size.setObjectName(u"start_size")
        self.start_size.setGeometry(QRect(200, 240, 101, 41))
        self.start_size.setFont(font1)
        self.start_size.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start_size.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start_size.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start_size.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start_size.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start_size.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : #3A4044;\n"
"color : #A9B5BD;\n"
"border: 1px solid #A9B5BD; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68)\n"
"}")
        self.label_19 = QLabel(self.exrSize)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 60, 491, 31))
        self.label_19.setFont(font2)
#if QT_CONFIG(tooltip)
        self.label_19.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_19.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_19.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_19.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_19.setStyleSheet(u"color : #A9B5BD;\n"
"font-weight : 300;\n"
"background : transparent;")
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.exrSize)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 20, 481, 51))
        self.label_20.setFont(font3)
        self.label_20.setCursor(QCursor(Qt.ArrowCursor))
#if QT_CONFIG(tooltip)
        self.label_20.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_20.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_20.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_20.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_20.setStyleSheet(u"font-weight : 900;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.label_20.setAlignment(Qt.AlignCenter)
        self.Tab.addTab(self.exrSize, "")
        self.HI = QWidget()
        self.HI.setObjectName(u"HI")
        self.Done_thumb = QLabel(self.HI)
        self.Done_thumb.setObjectName(u"Done_thumb")
        self.Done_thumb.setGeometry(QRect(40, 210, 421, 31))
        self.Done_thumb.setFont(font4)
#if QT_CONFIG(tooltip)
        self.Done_thumb.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done_thumb.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done_thumb.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done_thumb.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done_thumb.setStyleSheet(u"color : rgb(140, 189, 154);\n"
"background : transparent;")
        self.Done_thumb.setAlignment(Qt.AlignCenter)
        self.thumb_warn = QLabel(self.HI)
        self.thumb_warn.setObjectName(u"thumb_warn")
        self.thumb_warn.setGeometry(QRect(-10, 60, 511, 31))
        self.thumb_warn.setFont(font2)
#if QT_CONFIG(tooltip)
        self.thumb_warn.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.thumb_warn.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.thumb_warn.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.thumb_warn.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.thumb_warn.setStyleSheet(u"color : #A9B5BD;\n"
"font-weight : 300;\n"
"background : transparent;")
        self.thumb_warn.setAlignment(Qt.AlignCenter)
        self.start_thumb = QPushButton(self.HI)
        self.start_thumb.setObjectName(u"start_thumb")
        self.start_thumb.setGeometry(QRect(200, 240, 101, 41))
        self.start_thumb.setFont(font1)
        self.start_thumb.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start_thumb.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start_thumb.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start_thumb.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start_thumb.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start_thumb.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : #3A4044;\n"
"color : #A9B5BD;\n"
"border: 1px solid #A9B5BD; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(169, 181, 189);\n"
"color : rgb(58, 64, 68)\n"
"}")
        self.thumb_title = QLabel(self.HI)
        self.thumb_title.setObjectName(u"thumb_title")
        self.thumb_title.setGeometry(QRect(0, 20, 491, 51))
        self.thumb_title.setFont(font3)
#if QT_CONFIG(tooltip)
        self.thumb_title.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.thumb_title.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.thumb_title.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.thumb_title.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.thumb_title.setStyleSheet(u"font-weight : 900;\n"
"color : #A9B5BD;\n"
"background : transparent;")
        self.thumb_title.setAlignment(Qt.AlignCenter)
        self.label_movPath = QLabel(self.HI)
        self.label_movPath.setObjectName(u"label_movPath")
        self.label_movPath.setGeometry(QRect(40, 170, 111, 21))
        self.label_movPath.setFont(font8)
#if QT_CONFIG(tooltip)
        self.label_movPath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_movPath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_movPath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_movPath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_movPath.setStyleSheet(u"color : rgb(169, 181, 189);\n"
"background : transparent;")
        self.label_movPath.setAlignment(Qt.AlignCenter)
        self.label_thumb = QLabel(self.HI)
        self.label_thumb.setObjectName(u"label_thumb")
        self.label_thumb.setGeometry(QRect(340, 170, 111, 21))
        self.label_thumb.setFont(font8)
#if QT_CONFIG(tooltip)
        self.label_thumb.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_thumb.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_thumb.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_thumb.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_thumb.setStyleSheet(u"color : rgb(169, 181, 189);\n"
"background : transparent;")
        self.label_thumb.setAlignment(Qt.AlignCenter)
        self.thumbPath = QPushButton(self.HI)
        self.thumbPath.setObjectName(u"thumbPath")
        self.thumbPath.setGeometry(QRect(350, 130, 91, 41))
        self.thumbPath.setFont(font1)
        self.thumbPath.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.thumbPath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.thumbPath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.thumbPath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.thumbPath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.thumbPath.setStyleSheet(u"QPushButton {\n"
"border-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.movPath = QPushButton(self.HI)
        self.movPath.setObjectName(u"movPath")
        self.movPath.setGeometry(QRect(50, 130, 91, 41))
        self.movPath.setFont(font1)
        self.movPath.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.movPath.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.movPath.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.movPath.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.movPath.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.movPath.setStyleSheet(u"QPushButton {\n"
"border-radius: 7px;\n"
"background : #A9B5BD;\n"
"color : rgb(58, 64, 68); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(135, 144, 151)\n"
"}")
        self.thumb_title_2 = QLabel(self.HI)
        self.thumb_title_2.setObjectName(u"thumb_title_2")
        self.thumb_title_2.setGeometry(QRect(188, 130, 125, 47))
        font9 = QFont()
        font9.setFamilies([u"Roboto Flex"])
        font9.setPointSize(14)
        font9.setBold(True)
        font9.setItalic(False)
        self.thumb_title_2.setFont(font9)
#if QT_CONFIG(tooltip)
        self.thumb_title_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.thumb_title_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.thumb_title_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.thumb_title_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.thumb_title_2.setStyleSheet(u"font-weight : 900;\n"
"color : rgb(131, 140, 148);\n"
"background : transparent;")
        self.thumb_title_2.setAlignment(Qt.AlignCenter)
        self.Tab.addTab(self.HI, "")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 541, 51))
        font10 = QFont()
        font10.setFamilies([u"Roboto Flex"])
        font10.setPointSize(24)
        font10.setBold(True)
        font10.setItalic(False)
        self.label_7.setFont(font10)
        self.label_7.setCursor(QCursor(Qt.ArrowCursor))
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_7.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_7.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_7.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_7.setStyleSheet(u"font-weight : 900;\n"
"color : rgb(58, 64, 68);\n"
"background : transparent;")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 60, 561, 41))
        font11 = QFont()
        font11.setFamilies([u"Helvetica-Light"])
        font11.setPointSize(13)
        font11.setBold(False)
        font11.setItalic(False)
        self.label_9.setFont(font11)
#if QT_CONFIG(tooltip)
        self.label_9.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_9.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_9.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_9.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_9.setStyleSheet(u"\n"
"color : rgb(58, 64, 68);\n"
"background : transparent;")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(170, 450, 231, 61))
        self.label_18.setFont(font11)
#if QT_CONFIG(tooltip)
        self.label_18.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_18.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_18.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_18.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_18.setStyleSheet(u"\n"
"color : rgb(129, 142, 153);\n"
"background : transparent;")
        self.label_18.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.Tab.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tool Archives", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"TC \uc815\ubcf4 \ucc38\uace0\uc6a9 / xml2xlsx\uc640 \ub354\ube14\uccb4\ud06c\ud558\uae30", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"EDL 2 XLSX", None))
        self.start_e2x.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Done_e2x.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.upload_e2x.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"EDL File", None))
        self.Tab.setTabText(self.Tab.indexOf(self.edl2xlsx), QCoreApplication.translate("MainWindow", u"edl2xlsx", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"XML 2 XLSX", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\ub9ac\ud0c0\uc784, \ub9ac\uc0ac\uc774\uc988 \uc815\ubcf4\ub9cc \ucc38\uace0\ud558\uae30 / TC\ub294 edl\ub85c.", None))
        self.start_x2x.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Done_x2x.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"XML File", None))
        self.upload_x2x.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.Tab.setTabText(self.Tab.indexOf(self.xml2xlsx), QCoreApplication.translate("MainWindow", u"xml2xlsx", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"FOLDER/FILE RENAME", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\uc5d1\uc140\uc5d0\uc11c \uc624\ub984\ucc28\uc21c \uc815\ub82c \ud544\uc218\ub85c \ud558\uae30 + \ud234 \uc2e4\ud589 \uc804 \ub354\ube14\uccb4\ud06c \ud544\uc218", None))
        self.start_RN.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Done_RN.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.list_RN.setText(QCoreApplication.translate("MainWindow", u"Xlsx List", None))
        self.list_label_RN.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.ext_path.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Filename Extension", None))
        self.folder_label_RN.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.folder_RN_2.setText(QCoreApplication.translate("MainWindow", u"Folder", None))
        self.Tab.setTabText(self.Tab.indexOf(self.rename), QCoreApplication.translate("MainWindow", u"rename", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"SEQUENCE BURN-IN", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Basic Text \ub85c \ub450\uc9c0 \ub9d0 \uac83 !!!", None))
        self.start_BI.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Done_BI.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.list_BI.setText(QCoreApplication.translate("MainWindow", u"Xlsx List", None))
        self.xml_BI.setText(QCoreApplication.translate("MainWindow", u"fcpxml", None))
        self.list_label_BI.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.xml_label_BI.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.shot_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type SEQ name", None))
        self.Tab.setTabText(self.Tab.indexOf(self.burnIn), QCoreApplication.translate("MainWindow", u"burn-in", None))
        self.exrpath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"exr path", None))
        self.Done_size.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"EXR path", None))
        self.upload_pc_2.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.start_size.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Plate list \uc791\uc131 \uc2dc plate-resolution \uae30\uc785", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"EXR Resolution Check", None))
        self.Tab.setTabText(self.Tab.indexOf(self.exrSize), QCoreApplication.translate("MainWindow", u"exr size", None))
        self.Done_thumb.setText(QCoreApplication.translate("MainWindow", u"DONE", None))
        self.thumb_warn.setText(QCoreApplication.translate("MainWindow", u"\ucd9c\ub825 \uc911\uc778 \uc378\ub124\uc77c\uc740 \ud074\ub9ad X (\uc27d\uac8c \ub809\uac78\ub824\uc694)", None))
        self.start_thumb.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.thumb_title.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Export", None))
        self.label_movPath.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.label_thumb.setText(QCoreApplication.translate("MainWindow", u"CHECK YOUR DESKTOP", None))
        self.thumbPath.setText(QCoreApplication.translate("MainWindow", u"Thumbnail", None))
        self.movPath.setText(QCoreApplication.translate("MainWindow", u"MOV", None))
        self.thumb_title_2.setText(QCoreApplication.translate("MainWindow", u"loading ... \n"
" STD_1234.mov", None))
        self.Tab.setTabText(self.Tab.indexOf(self.HI), QCoreApplication.translate("MainWindow", u"thumbnail", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"TOOL ARCHIVES", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"latest. 2023.03.16", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"MADE. SEOYEONSU", None))
    # retranslateUi

