# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '1031.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(422, 567)
        font = QFont()
        font.setFamilies([u"KOTRA_BOLD"])
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color :rgb(255, 255, 255)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.folder_path = QLineEdit(self.centralwidget)
        self.folder_path.setObjectName(u"folder_path")
        self.folder_path.setGeometry(QRect(50, 181, 251, 41))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 216))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(249, 249, 249, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(1, 1, 1, 216))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush3 = QBrush(QColor(65, 65, 65, 63))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush5 = QBrush(QColor(255, 255, 255, 63))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.folder_path.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Roboto Flex"])
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.folder_path.setFont(font1)
        self.folder_path.setMouseTracking(True)
        self.folder_path.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.folder_path.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.folder_path.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.folder_path.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.folder_path.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.folder_path.setAutoFillBackground(False)
        self.folder_path.setStyleSheet(u"border-top-left-radius : 7px;\n"
"border-bottom-left-radius: 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px; ")
        self.folder_path.setInputMask(u"")
        self.folder_path.setText(u"")
        self.folder_path.setFrame(False)
        self.folder_path.setDragEnabled(True)
        self.folder_path.setReadOnly(True)
        self.folder_path.setPlaceholderText(u"")
        self.folder_path.setClearButtonEnabled(False)
        self.folder_select = QPushButton(self.centralwidget)
        self.folder_select.setObjectName(u"folder_select")
        self.folder_select.setGeometry(QRect(300, 181, 71, 41))
        font2 = QFont()
        font2.setFamilies([u"SUIT"])
        font2.setBold(True)
        self.folder_select.setFont(font2)
        self.folder_select.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.folder_select.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.folder_select.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.folder_select.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.folder_select.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.folder_select.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : white;\n"
"border : 1.3px solid rgb(213, 213, 213);\n"
"color : rgb(147, 147, 147); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(91, 134, 255);\n"
"	border :1.3px solid rgb(91, 134, 255);\n"
"}")
        self.ext_path = QLineEdit(self.centralwidget)
        self.ext_path.setObjectName(u"ext_path")
        self.ext_path.setGeometry(QRect(50, 380, 321, 41))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.ext_path.setPalette(palette1)
        font3 = QFont()
        font3.setFamilies([u"Roboto Flex"])
        self.ext_path.setFont(font3)
#if QT_CONFIG(tooltip)
        self.ext_path.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.ext_path.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.ext_path.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ext_path.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.ext_path.setStyleSheet(u"border-radius : 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px;")
        self.ext_path.setInputMask(u"")
        self.ext_path.setText(u"")
        self.ext_path.setReadOnly(False)
        self.ext_path.setPlaceholderText(u"\uc5c6\uc73c\uba74 \uc785\ub825 X")
        self.ext_path.setClearButtonEnabled(True)
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(160, 470, 101, 41))
        self.start.setFont(font2)
        self.start.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.start.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.start.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.start.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.start.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.start.setStyleSheet(u"QPushButton {border-radius: 7px;\n"
"background : rgb(91, 134, 255);\n"
"color : white; }\n"
"\n"
"QPushButton::hover {\n"
"	background : rgb(71, 104, 200);\n"
"}")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 141, 61, 41))
        font4 = QFont()
        font4.setFamilies([u"SUIT"])
        font4.setPointSize(16)
        font4.setBold(True)
        self.label.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label.setStyleSheet(u"font-weight : 600;\n"
"color : black")
        self.label.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 41, 411, 51))
        font5 = QFont()
        font5.setFamilies([u"Roboto Flex"])
        font5.setPointSize(32)
        font5.setBold(True)
        font5.setItalic(False)
        self.label_6.setFont(font5)
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_6.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_6.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_6.setStyleSheet(u"font-weight : 900;\n"
"color : black;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 340, 51, 41))
        font6 = QFont()
        font6.setFamilies([u"Roboto Flex"])
        font6.setPointSize(16)
        font6.setBold(True)
        self.label_2.setFont(font6)
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_2.setStyleSheet(u"font-weight : 600;\n"
"color : black;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 80, 421, 31))
        font7 = QFont()
        font7.setFamilies([u"Roboto Flex"])
        font7.setPointSize(14)
        font7.setBold(False)
        self.label_8.setFont(font7)
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_8.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_8.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_8.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_8.setStyleSheet(u"color : gray;\n"
"font-weight : 300;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.Done = QLabel(self.centralwidget)
        self.Done.setObjectName(u"Done")
        self.Done.setGeometry(QRect(0, 510, 421, 31))
        self.Done.setFont(font3)
#if QT_CONFIG(tooltip)
        self.Done.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Done.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Done.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Done.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.Done.setStyleSheet(u"color : green")
        self.Done.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 240, 71, 41))
        self.label_3.setFont(font4)
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_3.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_3.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_3.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.label_3.setStyleSheet(u"font-weight : 600;\n"
"color : black")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.rename_select = QPushButton(self.centralwidget)
        self.rename_select.setObjectName(u"rename_select")
        self.rename_select.setGeometry(QRect(300, 280, 71, 41))
        self.rename_select.setFont(font2)
        self.rename_select.setCursor(QCursor(Qt.PointingHandCursor))
#if QT_CONFIG(tooltip)
        self.rename_select.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.rename_select.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.rename_select.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.rename_select.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.rename_select.setStyleSheet(u"QPushButton {\n"
"border-top-right-radius : 7px;\n"
"border-bottom-right-radius: 7px;\n"
"background : white;\n"
"border : 1.3px solid rgb(213, 213, 213);\n"
"color : rgb(147, 147, 147); \n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	color : rgb(91, 134, 255);\n"
"	border :1.3px solid rgb(91, 134, 255);\n"
"}")
        self.rename_path = QLineEdit(self.centralwidget)
        self.rename_path.setObjectName(u"rename_path")
        self.rename_path.setGeometry(QRect(50, 280, 251, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.rename_path.setPalette(palette2)
        self.rename_path.setFont(font1)
        self.rename_path.setMouseTracking(True)
        self.rename_path.setTabletTracking(False)
#if QT_CONFIG(tooltip)
        self.rename_path.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.rename_path.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.rename_path.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.rename_path.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.rename_path.setAutoFillBackground(False)
        self.rename_path.setStyleSheet(u"border-top-left-radius : 7px;\n"
"border-bottom-left-radius: 7px;\n"
"background : rgb(249, 249, 249);\n"
"border : 1px solid rgb(231, 231, 231);\n"
"padding-left : 10px; ")
        self.rename_path.setInputMask(u"")
        self.rename_path.setText(u"")
        self.rename_path.setFrame(False)
        self.rename_path.setDragEnabled(True)
        self.rename_path.setReadOnly(True)
        self.rename_path.setPlaceholderText(u"Excel file ONLY")
        self.rename_path.setClearButtonEnabled(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Done.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.ext_path.raise_()
        self.folder_path.raise_()
        self.folder_select.raise_()
        self.start.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_3.raise_()
        self.rename_path.raise_()
        self.rename_select.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Renamer", None))
        self.folder_select.setText(QCoreApplication.translate("MainWindow", u"\uc120\ud0dd", None))
        self.start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\uc704 \ud3f4\ub354", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RENAMER", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\ud655\uc7a5\uc790", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"rename tool beta version 2022.10.31", None))
        self.Done.setText(QCoreApplication.translate("MainWindow", u"Done.", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ub9ac\ub124\uc784 \ud30c\uc77c", None))
        self.rename_select.setText(QCoreApplication.translate("MainWindow", u"\uc120\ud0dd", None))
    # retranslateUi

